### ISSUE TITLE
Identify how to protect gh-pages branch so that PR can push to it

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-schemas#248]
```
Push to branch gh-pages
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/nlpsandbox/nlpsandbox-schemas.git
 ! [remote rejected] HEAD -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/nlpsandbox/nlpsandbox-schemas.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by tschaffter** [comment]
It does not seem possible according to [this comment](https://github.community/t/allowing-github-actions-bot-to-push-to-protected-branch/16536/2).

**Comment by tschaffter** [comment]
Related to #240

**Comment by tschaffter** [comment]
The `gh-pages` can not be protected for now.
